from PyQt5 import QtCore, QtGui, QtWidgets
import sys

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(252, 631)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.M = QtWidgets.QLineEdit(self.centralwidget)
        self.M.setGeometry(QtCore.QRect(10, 70, 171, 31))
        self.M.setObjectName("Mass")
        self.R = QtWidgets.QLineEdit(self.centralwidget)
        self.R.setGeometry(QtCore.QRect(10, 110, 171, 31))
        self.R.setObjectName("R")
        self.r = QtWidgets.QLineEdit(self.centralwidget)
        self.r.setGeometry(QtCore.QRect(10, 150, 171, 31))
        self.r.setObjectName("r")
        self.m = QtWidgets.QLineEdit(self.centralwidget)
        self.m.setGeometry(QtCore.QRect(10, 190, 171, 31))
        self.m.setObjectName("m")
        self.I = QtWidgets.QLineEdit(self.centralwidget)
        self.I.setGeometry(QtCore.QRect(10, 230, 171, 31))
        self.I.setObjectName("I")
        self.g = QtWidgets.QLineEdit(self.centralwidget)
        self.g.setGeometry(QtCore.QRect(10, 270, 171, 31))
        self.g.setObjectName("g")
        self.y0 = QtWidgets.QLineEdit(self.centralwidget)
        self.y0.setGeometry(QtCore.QRect(10, 310, 171, 31))
        self.y0.setObjectName("y0")
        self.u = QtWidgets.QLineEdit(self.centralwidget)
        self.u.setGeometry(QtCore.QRect(10, 350, 171, 31))
        self.u.setObjectName("u")
        self.w = QtWidgets.QLineEdit(self.centralwidget)
        self.w.setGeometry(QtCore.QRect(10, 390, 171, 31))
        self.w.setObjectName("w")
        self.fi0 = QtWidgets.QLineEdit(self.centralwidget)
        self.fi0.setGeometry(QtCore.QRect(10, 430, 171, 31))
        self.fi0.setObjectName("fi0")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(190, 70, 41, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(190, 110, 41, 31))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(190, 150, 41, 31))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(190, 190, 41, 31))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(190, 230, 61, 31))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(190, 270, 51, 31))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(190, 310, 41, 31))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(190, 350, 41, 31))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(190, 390, 41, 31))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(190, 430, 51, 31))
        self.label_11.setObjectName("label_11")
        self.push1 = QtWidgets.QPushButton(self.centralwidget)
        self.push1.setGeometry(QtCore.QRect(10, 480, 111, 41))
        self.push1.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.push1.setObjectName("push1")
        self.push2 = QtWidgets.QPushButton(self.centralwidget)
        self.push2.setGeometry(QtCore.QRect(130, 480, 111, 41))
        self.push2.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.push2.setObjectName("push2")
        self.push3 = QtWidgets.QPushButton(self.centralwidget)
        self.push3.setGeometry(QtCore.QRect(10, 530, 111, 41))
        self.push3.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.push3.setObjectName("push3")
        self.push4 = QtWidgets.QPushButton(self.centralwidget)
        self.push4.setGeometry(QtCore.QRect(130, 530, 111, 41))
        self.push4.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.push4.setObjectName("push4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 211, 51))
        self.label.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 252, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.add_functions()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Rolling"))
        self.label_2.setText(_translate("MainWindow", "M, кг"))
        self.label_3.setText(_translate("MainWindow", "R, м"))
        self.label_4.setText(_translate("MainWindow", "r, м"))
        self.label_5.setText(_translate("MainWindow", "m, кг"))
        self.label_6.setText(_translate("MainWindow", "I, кг*м^2"))
        self.label_7.setText(_translate("MainWindow", "g, м/с^2"))
        self.label_8.setText(_translate("MainWindow", "y0, м"))
        self.label_9.setText(_translate("MainWindow", "u, м/c"))
        self.label_10.setText(_translate("MainWindow", "w, м/с"))
        self.label_11.setText(_translate("MainWindow", "fi0, рад"))
        self.push1.setText(_translate("MainWindow", "1"))
        self.push2.setText(_translate("MainWindow", "2"))
        self.push3.setText(_translate("MainWindow", "3"))
        self.push4.setText(_translate("MainWindow", "4"))
        self.label.setText(_translate("MainWindow", "Введите параметры:"))



    def add_functions(self):
        self.push1.clicked.connect(self.first)
        self.push2.clicked.connect(self.second)
        self.push3.clicked.connect(self.third)
        self.push4.clicked.connect(self.four)

    def first(self):
        a=int(self.M.text())
        b=int(self.R.text())
        print(a+b)

    def second(self):
        print(self.M.text(), self.R.text(), self.r.text(), self.m.text(), self.I.text(), self.g.text(),self.y0.text(), self.u.text(), self.w.text(), self.fi0.text())
    def third(self):
        print(self.M.text(), self.R.text(), self.r.text(), self.m.text(), self.I.text(), self.g.text(),self.y0.text(), self.u.text(), self.w.text(), self.fi0.text())
    def four(self):
        print(self.M.text(), self.R.text(), self.r.text(), self.m.text(), self.I.text(), self.g.text(),self.y0.text(), self.u.text(), self.w.text(), self.fi0.text())

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())